# 1) Create an 2D Array with numpy

In [1]:
import numpy as np

alist: list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Converting it into numpy matrix type
array_2D = np.array(alist)

print(array_2D)
print(type(array_2D))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


# 2) Inserting an element(1D array) in 2D array

In [ ]:
# only 1D array or list can be inserted in 2D array or matrix
# need insert(Array_name, position(row position or col position),[1D array], [axis(0 for row, 1 for col)])
new_2D_array = np.insert(array_2D, 0, [10, 20, 30], axis=1)

print(new_2D_array)
new_2D_array.shape

# using append(like insert it return an "new array" change not occur in parameter array)
# parameters = (array(in which to add), (1D array), axis)
new_2D_array = np.append(array_2D, [[10, 11, 12]], axis=0)
print(array_2D)
print(new_2D_array)

# 3) Accessing value of 2D array

In [ ]:
print(array_2D)
print(array_2D[1, 2])


def accessing_2D(array, row, col):
    if (row >= len(array) and col >= len(array[0])):
        raise ValueError("Out of Range Index")
    else:
        print(f"Value at array[{row}][{col}] = {array[row][col]}")


accessing_2D(array_2D, 1, 2)

# 4) Search in 2D Array

In [ ]:
print(array_2D)

def search(array, item : int):
    for row in range(len(array)):
        for col in range(len(array[0])):
            if array[row][col] == item:
                return f"Found at row {row}, col {col}"
    
    return "Not found"

result = search(array_2D, 10)
print("Result : ",result)

# 5) Delete from the 2D array

In [40]:
print(array_2D)

my_array = np.delete(array_2D, 1, axis=0)
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]
